"""
Constants used across the ResumeIQ AI parser modules.
"""

# Supported file extensions for resume parsing
SUPPORTED_EXTENSIONS = {".pdf", ".docx"}

# Section header keywords mapped to standard output keys
# Used for parsing and segmenting resumes by sections
SECTION_HEADERS = {
    "summary": [
        "summary",
        "professional summary",
        "profile",
        "professional profile",
        "about me",
        "objective",
        "career objective",
        "career goal",
        "career summary",
    ],
    "education": [
        "education",
        "academic background",
        "academic history",
        "academic qualifications",
        "academic qualification",
        "qualifications",
        "educational background",
        "education history",
    ],
    "experience": [
        "experience",
        "work experience",
        "professional experience",
        "employment history",
        "work history",
        "employment",
        "career history",
        "job history",
        "professional background",
        "work background",
    ],
    "projects": [
        "projects",
        "personal projects",
        "academic projects",
        "key projects",
        "notable projects",
        "recent projects",
        "featured projects",
    ],
    "certifications": [
        "certifications",
        "certificates",
        "credentials",
        "courses",
        "professional certifications",
        "accreditations",
        "licensures",
        "licenses & certifications",
    ],
    "languages": [
        "languages",
        "language proficiency",
        "languages spoken",
        "linguistic skills",
    ],
}

# Predefined soft skills list for keyword extraction
SOFT_SKILLS = [
    "communication",
    "teamwork",
    "leadership",
    "problem solving",
    "critical thinking",
    "adaptability",
    "time management",
    "conflict resolution",
    "creativity",
    "work ethic",
    "interpersonal skills",
    "collaboration",
    "emotional intelligence",
    "decision making",
    "negotiation",
    "presentation",
    "public speaking",
    "active listening",
    "empathy",
    "organization",
    "self-motivation",
    "stress management",
    "mentoring",
    "coaching",
    "customer service",
    "flexibility",
    "persuasion",
    "attention to detail",
    "dependability",
    "strategic thinking",
]

# Common languages for validation and extraction
LANGUAGES_LIST = [
    "english",
    "spanish",
    "french",
    "german",
    "mandarin",
    "cantonese",
    "chinese",
    "japanese",
    "korean",
    "russian",
    "arabic",
    "portuguese",
    "italian",
    "hindi",
    "bengali",
    "punjabi",
    "marathi",
    "telugu",
    "tamil",
    "gujarati",
    "urdu",
    "kannada",
    "odia",
    "malayalam",
    "vietnamese",
    "turkish",
    "polish",
    "dutch",
    "swedish",
    "norwegian",
    "danish",
    "finnish",
    "thai",
    "hebrew",
    "indonesian",
    "malay",
    "persian",
]
