"""
Predefined technical skills database used to extract skills from resumes.
Skills are organized by category to facilitate structured output.
"""

TECHNICAL_SKILLS_DB = {
    "Languages": [
        "Python",
        "Java",
        "C\\+\\+",  # Escaped for regex matching
        "C#",
        "C",
        "Go",
        "Golang",
        "Rust",
        "Swift",
        "Kotlin",
        "Ruby",
        "PHP",
        "JavaScript",
        "TypeScript",
        "HTML",
        "HTML5",
        "CSS",
        "CSS3",
        "SQL",
        "R",
        "MATLAB",
        "Scala",
        "Perl",
        "Shell",
        "Bash",
        "PowerShell",
        "Dart",
        "Objective-C",
        "Haskell",
        "Julia",
        "Solidity",
        "COBOL",
        "Fortran",
        "Lisp",
        "Prolog",
    ],
    "Frameworks": [
        "Django",
        "Flask",
        "FastAPI",
        "Spring Boot",
        "Spring",
        "ASP.NET",
        "Angular",
        "Vue",
        "Vue.js",
        "Svelte",
        "Next.js",
        "Nuxt.js",
        "Express",
        "Express.js",
        "NestJS",
        "Laravel",
        "Symfony",
        "Ruby on Rails",
        "Rails",
        "Gatsby",
        "Vite",
        "Tornado",
        "Masonite",
        "Sanic",
        "Flutter",
        "React Native",
        "Ionic",
        "Xamarin",
        "Electron",
        "Meteor",
    ],
    "Libraries": [
        "React",
        "React.js",
        "Redux",
        "jQuery",
        "Pandas",
        "NumPy",
        "SciPy",
        "Matplotlib",
        "Seaborn",
        "Scikit-Learn",
        "ScikitLearn",
        "BeautifulSoup",
        "Scrapy",
        "Requests",
        "SQLAlchemy",
        "Pydantic",
        "RxJava",
        "Lodash",
        "Axios",
        "D3.js",
        "Tailwind CSS",
        "Bootstrap",
    ],
    "Cloud": [
        "AWS",
        "Amazon Web Services",
        "Azure",
        "Microsoft Azure",
        "Google Cloud Platform",
        "GCP",
        "Heroku",
        "DigitalOcean",
        "Linode",
        "Firebase",
        "Vercel",
        "Netlify",
        "OpenStack",
        "Cloudflare",
        "OpenShift",
        "EC2",
        "S3",
        "Lambda",
    ],
    "Databases": [
        "PostgreSQL",
        "MySQL",
        "SQLite",
        "MongoDB",
        "Redis",
        "Cassandra",
        "Elasticsearch",
        "DynamoDB",
        "MariaDB",
        "Oracle",
        "Microsoft SQL Server",
        "MSSQL",
        "Neo4j",
        "Firebase Firestore",
        "Firestore",
        "InfluxDB",
        "Supabase",
        "CouchDB",
        "CockroachDB",
    ],
    "Developer Tools": [
        "Git",
        "GitHub",
        "GitLab",
        "Bitbucket",
        "Docker",
        "Kubernetes",
        "VS Code",
        "IntelliJ",
        "PyCharm",
        "Jira",
        "Confluence",
        "Postman",
        "WebStorm",
        "Eclipse",
        "Trello",
        "Slack",
        "Xcode",
        "Android Studio",
        "Figma",
    ],
    "AI Frameworks": [
        "PyTorch",
        "TensorFlow",
        "Keras",
        "Hugging Face",
        "Huggingface",
        "Transformers",
        "OpenCV",
        "spaCy",
        "NLTK",
        "LangChain",
        "LlamaIndex",
        "OpenAI",
        "Anthropic",
        "Cohere",
        "JAX",
        "TensorBoard",
        "MLflow",
        "XGBoost",
        "LightGBM",
    ],
    "DevOps": [
        "Jenkins",
        "GitHub Actions",
        "GitLab CI/CD",
        "CircleCI",
        "Travis CI",
        "Ansible",
        "Terraform",
        "Chef",
        "Puppet",
        "Prometheus",
        "Grafana",
        "ELK Stack",
        "Docker Swarm",
        "ArgoCD",
        "Nginx",
        "Apache",
        "Kubectl",
        "Helm",
    ],
}
